# Generated by Django 4.2.11 on 2026-04-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_jobmatchresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmatchresult',
            name='is_processing',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmatchresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmatchresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
